- service/models.py
- service/routes.py
> Add initial fields to schema

- service/models.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
> Model setup and tests

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
This pull request contains the following:
1. Updated table schema as below:
```
product_id = db.Column(db.Integer, primary_key=True, autoincrement=False)
name = db.Column(db.String(63), nullable=False)
condition = db.Column(db.Enum(Condition), nullable=False, default=Condition.NEW.name, primary_key=True)
quantity = db.Column(db.Integer, nullable=False, default=0)
reorder_quantity = db.Column(db.Integer, nullable=False, default=0)
restock_level = db.Column(db.Integer, nullable=False, default=0)
active = db.Column(db.Boolean, nullable=False, default=True)
created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
```
- earlier `Id` column has been renamed to `product_id` …
> inserting_product_in_inventoryDatabase

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
This PR contains the addition of `read inventory record `functionality. 
1. Functionality
Added `get_inventory_records:` to the routes.py file. This functionality takes `product ID` and `condition  ` as arguments from the user  and search the inventory database for the record and return the product id, name, quantity, condition, restock  level and reorder quantity. 
Here product d is passed in the URL and the condition is passed as part of the payload. These are used by the find function (present in the models.py file) to search for the particular record. 
2. Added the following test cases : 
- test_read_records
- test_read_non_existent_records 
Increased the routes.py code coverage from 95% to 100%.
> Added code and tests the read record functionality

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
This PR contains the implementation of the functionality to update an existing inventory record as a <b>PUT</b> request. The details of the implementation are as follows:<br>
Route: 
```
/inventory-records/<int:product_id>/<string:condition>
```
It takes <b>product_id</b> and <b>condition</b> as parameters in the URL and allows for the following 4 fields to be updated:
1. <i>quantity</i>
2. <i>reorder_quantity</i>
3. <i>restock_level</i>
4. <i>active</i>
The values for the field to be updated must be a part of the request body.<br>
This PR also contains two test functions implemented to test the aformentioned functionality namely:
1. <i>test_update_inventory_records</i>
2. <i>test_update_non_existent_inventory_records</i>
The ```test_update_inventory_records``` function creates a single …
> Update API functionality

- service/routes.py
- tests/test_models.py
- tests/test_routes.py
This PR contains the addition of `Delete inventory record` functionality. 
1. Functionality
Add `delete_inventory_record` to delete an existing record.
2. Tested the following changes using unit tests : 
- `test_delete_inventory_record_success`
- `test_delete_inventory_record_exception` 
Code coverage: 
`service/models 94%`
`service/routes 100%`
> Add delete record function

- service/models.py
- tests/test_models.py
This PR contains the addition of additional tests for deserialize function.
Functionality
Add `test_deserialize_type_bad_data` to test bad data
Code coverage: 95% :)
> Add additional tests for deserialize

- service/common/error_handlers.py
- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Changes:
1. The method ```update_inventory_records``` in routes.py has been modified to accept values >= 0
2. It also accept updates for the field <i>name</i> and also tests for attempts to update with invalid value.
3. There is also a test added to update a record that does not exist which returns error code 404.
4. Code conforms to PEP8 standard
> Revisited Update API and other modifications

- service/common/error_handlers.py
- service/models.py
- service/routes.py
The code in models and routes has been linted. Only the inventory deserializer needs to be decomplicated @aayushagrawal135.
> Linted most of the code in models and routes

- tests/test_routes.py
This pull request contains tests for checking that methods are not allowed.
Example:
- Calling a post request with product id
- Calling a delete and put request without product id
> Test implemented for incorrect method calls

- service/routes.py
- tests/test_routes.py
> Add health endpoint

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
This pull request contains the following:
1. Contains the code to add a filter to the query to fetch an inventory record based on
- Name
- Condition
- Active (search all records which are available and are not soft deleted)
- Quantity
2. Code coverage of 97%
> Add query strings

- README.md
- service/models.py
- service/routes.py
- tests/test_routes.py
This pull request contains the following:
```
- Fix for wrong error code on DELETE operations
- Change query method on DELETE
```
Code coverage is 96%
> Add fix for wrong DELETE codes

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Implemented checkout feature and corresponding tests. Added support for the ```active``` field in the Inventory Model for most routes and tests. Also added condition in update and checkout URLs
> Add Checkout feature

- README.md
- service/routes.py
- tests/test_routes.py
The condition of the product, no longer needs to be passed in the payload while trying to read a record.
> Update the read bug

- service/routes.py
This PR is a simple fix for issue #34 using `app.url_map.strict_slashes = False`
> Add extra slash url feature

- service/common/error_handlers.py
- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
This PR adds changes to update, checkout, create and deserialize with changes in tests.
Coverage = 95%
> Refactor codebase for create, update and checkout

- service/static/index.html
- service/static/js/rest_api.js
This pull request contains the code to search for a record using the user interface.
> Added the search ui

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Refactored Checkout and Reorder functions into Flask-RESTX and linted code in all files. Improved routes.py coverage to 98%
> Refactored Checkout and Reorder for Rest-X

- .devcontainer/Dockerfile
- Makefile
- features/environment.py
- features/inventory.feature
- features/steps/inventory_steps.py
- features/steps/web_steps.py
- requirements.txt
- service/static/index.html
- service/static/js/rest_api.js
This pull request contains, BDD test to create a record.
> Implemented BDD test to create a record. 

- features/inventory.feature
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
Added BDD tests for :
1. Update
2. Delete
3. Checkout
4. Reorder
5. Search
> Added more BDD tests 

- .github/workflows/bdd.yml
> Added BDD.yml

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
> Add test-cases for deserialize and query inventory

- service/models.py
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Removed reorder_quantity and restock_level database attributes
> Remove extra attributes

- service/static/js/rest_api.js
Updated the ajax failure errors when UI cannot be processed
> Updated the ajax failure errors
